package com.serial;

public interface Checksum {
    /**
     * return a byte[] containing the checksum of the plaintext array
     */
    byte[] calc(byte[] plaintext);

    /**
     * return the length of a sum generated by this object
     */
    int length();
}
